Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -4,6 +4,9 @@ on:
   push:
     branches:
       - main  # Trigger the workflow only on pushes to the main branch
+    paths-ignore:
+      - README.md
+      - LICENSE
 
 jobs:
   build:
@@ -21,7 +24,7 @@ jobs:
       - name: Install dependencies
         run: |
           python -m pip install --upgrade pip
-          pip install PyQt5 PyQtWebEngine  # Install your dependencies
+          pip install pyqt5 pyqt5-qtwebengine  # Install your dependencies
 
       - name: Install Xvfb
         run: sudo apt-get install -y xvfb  # Install Xvfb
@@ -31,7 +34,7 @@ jobs:
           mkdir -p tests  # Create tests directory if it doesn't exist
           Xvfb :99 -screen 0 1024x768x24 &  # Start Xvfb in the background
           export DISPLAY=:99  # Set the DISPLAY environment variable
-          python main.py > tests/output.log 2>&1  # Run the application and capture output and errors
+          python main.py > tests/output.log 2>&1 || (echo "Application crashed with exit code $?"; cat tests/output.log)  # Run the application and capture output and errors
 
       - name: Package application
         run: |
